import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";

export interface DocSection {
  heading: string;
  content: string;
}

export interface GeneratedDocument {
  title: string;
  sections: DocSection[];
}

function parseContentToParagraphs(content: string): Paragraph[] {
  const lines = content.split("\n").filter((l) => l.trim() !== "");
  return lines.map((line) => {
    const isBullet = line.trim().startsWith("•") || line.trim().startsWith("-");
    return new Paragraph({
      text: isBullet ? line.trim() : line.trim(),
      bullet: isBullet ? { level: 0 } : undefined,
      spacing: { after: 80 },
    });
  });
}

export async function buildWordDoc(
  documents: GeneratedDocument[],
  teamName: string,
  categoryName: string,
  companyName: string
): Promise<Blob> {
  const sections: object[] = [];

  for (const doc of documents) {
    // Document title
    sections.push(
      new Paragraph({
        text: doc.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC", space: 4 },
        },
      })
    );

    // Metadata row
    sections.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${companyName} · ${teamName} · ${categoryName}`, color: "888888", size: 18 }),
        ],
        spacing: { after: 300 },
      })
    );

    for (const section of doc.sections) {
      sections.push(
        new Paragraph({
          text: section.heading,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 120 },
        })
      );
      sections.push(...parseContentToParagraphs(section.content));
    }

    // Page break between documents
    sections.push(new Paragraph({ pageBreakBefore: true }));
  }

  const wordDoc = new Document({
    creator: "CosmoLab AI",
    title: `${teamName} Discovery Documents`,
    description: `Generated by CosmoLab AI for ${companyName}`,
    sections: [{ children: sections as Paragraph[] }],
  });

  const buffer = await Packer.toBlob(wordDoc);
  return buffer;
}
